// Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
	IIconOptions,
	IIconSubset,
	registerIcons
} from '@fluentui/react/lib/Styling';

export function initializeIcons(
	baseUrl: string = '',
	options?: IIconOptions
): void {
	const subset: IIconSubset = {
		style: {
			MozOsxFontSmoothing: 'grayscale',
			WebkitFontSmoothing: 'antialiased',
			fontStyle: 'normal',
			fontWeight: 'normal',
			speak: 'none'
		},
		fontFace: {
			fontFamily: `"FabricMDL2Icons"`,
			src: `url('${baseUrl}fabric-icons.woff') format('woff')`
		},
		icons: {
			'Accept': '\uE8FB',
			'AcceptMedium': '\uF78C',
			'AccountActivity': '\uEFF4',
			'ActivityFeed': '\uF056',
			'Add': '\uE710',
			'AddBookmark': '\uF5B7',
			'AddFavorite': '\uF0C8',
			'AddFavoriteFill': '\uF0C9',
			'AddField': '\uE4C7',
			'AddIn': '\uF775',
			'AddLink': '\uE35E',
			'AddMedium': '\uECA1',
			'AddMultiple': '\uE9C5',
			'AddNotes': '\uEAE3',
			'AddOnlineMeeting': '\uED8E',
			'AddTo': '\uECC8',
			'AddToShoppingList': '\uEA9A',
			'AlarmClock': '\uE919',
			'Album': '\uE7AB',
			'AlbumRemove': '\uEC62',
			'AlertSettings': '\uF8B6',
			'AppIconDefaultAdd': '\uEFDA',
			'ArrowTallDownLeft': '\uF2BF',
			'ArrowTallDownRight': '\uF2C0',
			'ArrowTallUpLeft': '\uF2BD',
			'ArrowTallUpRight': '\uF2BE',
			'ArrowUpRight': '\uF069',
			'Ascending': '\uEDC0',
			'Attach': '\uE723',
			'AutoRacing': '\uEB24',
			'Back': '\uE72B',
			'BackToWindow': '\uE73F',
			'BoxAdditionSolid': '\uF2D4',
			'BoxPlaySolid': '\uF2D6',
			'BulkUpload': '\uF548',
			'BulletedList2': '\uF2C7',
			'BulletedList2Mirrored': '\uF2C8',
			'BulletedTreeList': '\uF84C',
			'CaloriesAdd': '\uF172',
			'CheckboxComposite': '\uE73A',
			'CheckboxCompositeReversed': '\uE73D',
			'CheckboxIndeterminateCombo': '\uF16E',
			'CheckList': '\uE9D5',
			'CheckListCheck': '\uF7A9',
			'ChevronDown': '\uE70D',
			'ChevronDownEnd': '\uF5E4',
			'ChevronDownMed': '\uE972',
			'ChevronLeft': '\uE76B',
			'ChevronRight': '\uE76C',
			'ChevronUpEnd': '\uE55B',
			'ChevronUpMed': '\uE971',
			'CircleAddition': '\uF2E3',
			'CircleAdditionSolid': '\uF2E4',
			'CirclePause': '\uF2D9',
			'CirclePauseSolid': '\uF2D8',
			'ClipboardList': '\uF0E3',
			'ClipboardListAdd': '\uE4EF',
			'CloudAdd': '\uECA9',
			'CloudDownload': '\uEBD3',
			'CloudEdit': '\uE4C8',
			'CloudImportExport': '\uEE55',
			'CodeEdit': '\uF544',
			'Combine': '\uEDBB',
			'Combobox': '\uF516',
			'CommandPrompt': '\uE756',
			'Comment': '\uE90A',
			'CommentActive': '\uF804',
			'CommentAdd': '\uF2B3',
			'CommentNext': '\uF2B4',
			'CommentPrevious': '\uF2B5',
			'CommentSolid': '\uE30E',
			'CommentUrgent': '\uF307',
			'CompassNW': '\uE942',
			'Completed': '\uE930',
			'Completed12': '\uE559',
			'CompletedSolid': '\uEC61',
			'ComplianceAudit': '\uE369',
			'DashboardAdd': '\uF52D',
			'DefaultSettings': '\uF648',
			'Delete': '\uE74D',
			'DensityComfy': '\uE4BA',
			'DependencyAdd': '\uE344',
			'Descending': '\uEDC1',
			'Dislike': '\uE8E0',
			'DoubleChevronDown': '\uEE04',
			'DoubleChevronLeft': '\uEDBE',
			'DoubleChevronLeftMed': '\uE991',
			'DoubleChevronRight': '\uEDBF',
			'DoubleChevronUp': '\uEDBD',
			'DoubleDownArrow': '\uF769',
			'Down': '\uE74B',
			'Download': '\uE896',
			'DownloadDocument': '\uF549',
			'DrillDown': '\uF532',
			'DrillDownSolid': '\uF533',
			'Dropdown': '\uEDC5',
			'EaseOfAccess': '\uE776',
			'Edit': '\uE70F',
			'EditContact': '\uEFD3',
			'EditListPencil': '\uE61B',
			'EditMail': '\uEF61',
			'EditPhoto': '\uEF77',
			'EditStyle': '\uEF60',
			'EmojiDisappointed': '\uEA88',
			'Equalizer': '\uE9E9',
			'Error': '\uE783',
			'ErrorBadge': '\uEA39',
			'ExpandAll': '\uF859',
			'ExpandMenu': '\uEF67',
			'ExploreContent': '\uECCD',
			'ExploreContentSingle': '\uF164',
			'ExploreData': '\uF5B6',
			'FabricTextHighlightComposite': '\uF7DA',
			'FastForward': '\uEB9D',
			'FastMode': '\uF19A',
			'FavoriteList': '\uE728',
			'FavoriteStar': '\uE734',
			'FileComment': '\uF30F',
			'FileImage': '\uF311',
			'FileOff': '\uE3FC',
			'FilePDB': '\uF2E5',
			'FileSystem': '\uE433',
			'Filter': '\uE71C',
			'FilterAscending': '\uF21A',
			'FilterDescending': '\uF21B',
			'Filters': '\uE795',
			'FilterSettings': '\uF76C',
			'FolderList': '\uF2CE',
			'FolderListMirrored': '\uF2CF',
			'GroupedList': '\uEF74',
			'GroupList': '\uF168',
			'GroupObject': '\uF4F1',
			'Info': '\uE946',
			'InputAddress': '\uE41E',
			'Link': '\uE71B',
			'Link12': '\uF6E3',
			'LinkedDatabase': '\uF779',
			'Mail': '\uE715',
			'MailLink': '\uEFAC',
			'MarketDown': '\uEF42',
			'MediaAdd': '\uF510',
			'MiniExpand': '\uE93A',
			'MiniExpandMirrored': '\uEA5A',
			'MiniLink': '\uE732',
			'ModelAppTemplate32': '\uE5FD',
			'MusicInCollection': '\uE940',
			'Next': '\uE893',
			'NumberedList': '\uEA1C',
			'ODLink': '\uE4BB',
			'ODLink12': '\uE4BC',
			'PageAdd': '\uEA1A',
			'PageEdit': '\uEFB6',
			'PageLeft': '\uE760',
			'PageListFilter': '\uF813',
			'PageRight': '\uE761',
			'Pause': '\uE769',
			'Photo2Add': '\uECAB',
			'PhotoError': '\uE3F7',
			'Play': '\uE768',
			'PlaybackRate1x': '\uEC57',
			'PlayerSettings': '\uEF58',
			'PlaylistMusic': '\uE93F',
			'PlayResume': '\uF2C6',
			'PlayReverse': '\uF3E5',
			'PlayReverseResume': '\uF3E4',
			'PlaySolid': '\uF5B0',
			'PopExpand': '\uE49A',
			'Previous': '\uE892',
			'ProcessingPause': '\uE405',
			'PublishContent': '\uF0D4',
			'Puzzle': '\uEA86',
			'QueryList': '\uF2B8',
			'RemoveLink': '\uED90',
			'RepeatAll': '\uE8EE',
			'RepeatOne': '\uE8ED',
			'RightDoubleQuote': '\uE9B1',
			'ScaleVolume': '\uF18C',
			'ScrollUpDown': '\uEC8F',
			'Search': '\uE721',
			'Settings': '\uE713',
			'SettingsAdd': '\uE35A',
			'SettingsSync': '\uE359',
			'SingleColumnEdit': '\uF321',
			'SortDown': '\uEE69',
			'SortUp': '\uEE68',
			'StatusCircleErrorX': '\uF13D',
			'StatusCircleQuestionMark': '\uF142',
			'Stopwatch': '\uE916',
			'StreamPlaylist': '\uE669',
			'SyncError': '\uEA6A',
			'System': '\uE770',
			'TagGroup': '\uE3F6',
			'TaskList': '\uE3B6',
			'TextDocumentEdit': '\uE43B',
			'ToggleLeft': '\uF19E',
			'ToggleRight': '\uF19F',
			'Uneditable': '\uED1D',
			'Uneditable2': '\uF876',
			'Up': '\uE74A',
			'UpdateRestore': '\uE777',
			'Upload': '\uE898',
			'UserWarning': '\uE368',
			'VideoAdd': '\uE430',
			'Volume0': '\uE992',
			'Volume1': '\uE993',
			'Volume2': '\uE994',
			'Volume3': '\uE995',
			'VolumeDisabled': '\uEA85',
			'WaitlistConfirm': '\uF550',
			'Warning': '\uE7BA',
			'Warning12': '\uF62F'
		}
	};

	registerIcons(subset, options);
}


export function initializeCusIcons(
	baseUrl: string = '',
	options?: IIconOptions
): void{
	const subset: IIconSubset = {
		style: {
			MozOsxFontSmoothing: 'grayscale',
			WebkitFontSmoothing: 'antialiased',
			fontStyle: 'normal',
			fontWeight: 'normal',
			speak: 'none',
		},
		fontFace: {
			fontFamily: `"LxCusIcons"`,
			src: `url('${baseUrl}LxCusIcons.woff') format('woff')`,
		},
		icons: {
			Shuffle: '\uE001',
		}
	};

	registerIcons(subset, options);

}